### PR TITLE
fix: update first_id logic to use the oldest answer item in chat messages

### LINKED ISSUE #23971: The logs drawer always loading
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

**in the logs page, click the conversation,when open the drawer,we can view the logs,but when it over the limit (10), the drawer always in loading status**

Image

Image

Image

### ✔️ Expected Behavior

it can load more logs 

### ❌ Actual Behavior

the  logs can't load when it over the limit 10

### PR DESCRIPTION
**Pull request by liugddx**
…ages

> [!IMPORTANT]
>
> 1. Make sure you have read our [contribution guidelines](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md)
> 2. Ensure there is an associated issue and you have been assigned to it
> 3. Use the correct syntax to link this PR: `Fixes #<issue number>`.
Close  #23971 
close https://github.com/langgenius/dify/pull/24003

## Summary

1. Optimized Pagination Logic
- Updated first_id parameter to use the oldest answer item instead of the first chat message
- Fixed the perpetual loading issue when conversation history exceeds 10 messages
2. Enhanced Data Handling
-  Added detection and filtering for duplicate messages
-  Implemented fallback logic when answer items are not available
-  Added retry mechanism with alternative ID when initial loading returns duplicates
3. Improved Error Handling
- Added proper error catching and state management
- Enhanced logging for better debugging and maintenance

## Screenshots

| Before | After |
|--------|-------|
| ...    | ...   |

## Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

File: web/app/components/app/log/list.tsx [hunk 1]
```diff
@@ -8,7 +8,7 @@ import {
 } from '@heroicons/react/24/outline'
 import { RiCloseLine, RiEditFill } from '@remixicon/react'
 import { get } from 'lodash-es'
-import InfiniteScroll from 'react-infinite-scroll-component'
+// import InfiniteScroll from 'react-infinite-scroll-component'
```
Comment (crazywoola) [inline web/app/components/app/log/list.tsx]:
```suggestion
```

**Review by crazywoola — APPROVED** [review]
