### PR TITLE
Fix the bug of automatically appending basepath to image resource.

### LINKED ISSUE #24209: some resource address access returns 404.
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.2

### Cloud or Self Hosted

Self Hosted (Source), Self Hosted (Docker)

### Steps to reproduce

After configuring the basepath, some img resource address access returns 404.

### ✔️ Expected Behavior

Normal access

### ❌ Actual Behavior

_No response_

### PR DESCRIPTION
**Pull request by 17hz**
> [!IMPORTANT]
>
> 1. Make sure you have read our [contribution guidelines](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md)
> 2. Ensure there is an associated issue and you have been assigned to it
> 3. Use the correct syntax to link this PR: `Fixes #<issue number>`.

## Summary

Fixes #24209

## Screenshots

| Before | After |
|--------|-------|
| Image   | Image  |

## Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

File: web/app/routePrefixHandle.tsx [hunk 1]
```diff
@@ -10,7 +10,7 @@ export default function RoutePrefixHandle() {
     const addPrefixToImg = (e: HTMLImageElement) => {
       const url = new URL(e.src)
       const prefix = url.pathname.slice(0, basePath.length)
-      if (prefix !== basePath && !url.href.startsWith('blob:') && !url.href.startsWith('data:')) {
+      if (prefix !== basePath && !url.href.startsWith('blob:') && !url.href.startsWith('data:') && !url.href.startsWith('http')) {
```
Comment (crazywoola) [inline web/app/routePrefixHandle.tsx:13]: `https` maybe you should check it as well. :)

Comment (17hz) [reply web/app/routePrefixHandle.tsx:13]: This condition covers both `http` and `https`.

**Comment by crazywoola** [comment]
Please link an existing issue or create one in the description.

**Comment by 17hz** [comment]
done

**Review by crazywoola — APPROVED** [review]
