### PR TITLE
fix: fix tool type is miss

### LINKED ISSUE #32149: Agent Node fails with PluginNotFoundError when using Workflow-as-Tool after upgrade from 1.9.1 to 1.12.1
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Have a working Dify 1.9.1 instance with:
   - Multiple workflows published as tools (workflow-as-tools)
   - Agent nodes (FunctionCalling strategy) in chatflows/workflows that use these workflow-as-tools
2. Upgrade to Dify 1.12.1 following the standard Docker Compose upgrade process
3. Run the plugin migration commands:
   ```bash
   uv run flask extract-plugins --workers=20
   uv run flask install-plugins --workers=2
   uv run flask migrate-data-for-plugin
   ```
4. Run any workflow containing an Agent node that references a workflow-as-tool

### ✔️ Expected Behavior

The Agent node should correctly resolve workflow-as-tools and execute them via `ToolProviderType.WORKFLOW` path in `tool_manager.py`.

### ❌ Actual Behavior

The Agent node fails with:

```
PluginNotFoundError: plugin not found
```

The Agent node treats workflow-as-tools as `BUILT_IN` plugins and attempts to resolve them through the plugin daemon, which does not have them registered.

## Root Cause Analysis

The issue is in `api/core/workflow/nodes/agent/agent_node.py`, line 262:

```python
provider_type = ToolProviderType(tool.get("type", ToolProviderType.BUILT_IN))
```

When workflow-as-tools are saved through the UI into the Agent node configuration, the `"type"` field is **not included** in the tool dictionary stored in the workflow graph JSON. The tool configuration only contains:

```json
{
  "provider_name": "52e7b8ce-eea9-4e6c-89d8-8946c809f1f1",
  "provider_show_name": "My Workflow Tool",
  "tool_name": "my_tool_name",
  "tool_label": "My Workflow Tool",
  "tool_description": "...",
  "settings": {},
  "parameters": { "query": { "auto": 1, "value": null } },
  "enabled": true,
  "extra": { "description": "..." }
}
```

**Notice the missing `"type": "workflow"` field.**

Because `"type"` is missing, the code defaults to `ToolProviderType.BUILT_IN`, which routes to `get_builtin_provider()` → `get_plugin_provider()` → plugin daemon lookup. Since workflow-as-tools are not registered in the plugin daemon's `tool_installations` table, it returns `plugin not found`.

The correct execution path should go through `ToolProviderType.WORKFLOW` (line 325 in `tool_manager.py`), which queries the `tool_workflow_providers` table directly:

```python
elif provider_type == ToolProviderType.WORKFLOW:
    workflow_provider_stmt = select(WorkflowToolProvider).where(...)
```

### 1. The workflow graph stores tools without `type` field

```sql
-- Query the active workflow graph
SELECT graph FROM workflows w 
JOIN apps a ON a.workflow_id = w.id 
WHERE a.id = '<app_id>';
```

The tool dictionary in `agent_parameters.tools.value[]` does not contain a `"type"` field.

### 2. The workflow-as-tools exist in `tool_workflow_providers` but NOT in plugin daemon

```sql
-- These exist (21 records):
SELECT id, name FROM tool_workflow_providers;

-- But plugin daemon only has marketplace plugins (10 records):
SELECT plugin_id, provider FROM tool_installations;  -- in dify_plugin DB
```

### 3. The plugin daemon confirms the lookup failure

```
plugin_daemon-1 | /app/internal/db/executor.go:259 record not found
plugin_daemon-1 | [0.335ms] [rows:0] SELECT * FROM "tool_installations" 
  WHERE tenant_id = '65758c17-...' 
  AND plugin_id = 'langgenius/52e7b8ce-eea9-4e6c-89d8-8946c809f1f1'
```

### 4. Traceback

```
File "/app/api/core/workflow/nodes/agent/agent_node.py", line 262
    provider_type = ToolProviderType(tool.get("type", ToolProviderType.BUILT_IN))
File "/app/api/core/workflow/nodes/agent/agent_node.py", line 286
    tool_runtime = ToolManager.get_agent_tool_runtime(...)
File "/app/api/core/tools/tool_manager.py", line 369
    tool_entity = cls.get_tool_runtime(...)
File "/app/api/core/tools/tool_manager.py", line 185
    provider_controller = cls.get_builtin_provider(provider_id, tenant_id)
File "/app/api/core/tools/tool_manager.py", line 114
    plugin_provider = cls.get_plugin_provider(provider, tenant_id)
File "/app/api/core/tools/tool_manager.py", line 144
    provider_entity = manager.fetch_tool_provider(tenant_id, provider)
→ PluginNotFoundError: plugin not found
```

### Option A: Fix in `agent_node.py` (auto-detect workflow tools)

When `type` is missing and defaults to `BUILT_IN`, check if the `provider_name` exists in `tool_workflow_providers` before proceeding:

```python
provider_type = ToolProviderType(tool.get("type", ToolProviderType.BUILT_IN))

# Auto-detect workflow-as-tools when type field is missing
if provider_type == ToolProviderType.BUILT_IN:
    from models.tools import WorkflowToolProvider
    from extensions.ext_database import db as _db
    _wf = _db.session.query(WorkflowToolProvider).filter_by(
        id=tool.get("provider_name", "")
    ).first()
    if _wf:
        provider_type = ToolProviderType.WORKFLOW
```

### Option B: Fix the frontend to save `type` field

Ensure the workflow editor saves `"type": "workflow"` in the Agent node's tool configuration when a workflow-as-tool is selected.

### Option C: Add workflow-as-tools to the migration script

The `flask migrate-data-for-plugin` command should also handle workflow-as-tools referenced in Agent nodes by adding the `"type": "workflow"` field to the graph JSON.

## Workaround

Manually update the workflow graph in the database to add the missing `type` field:

```sql
-- For each workflow-as-tool provider_id:
UPDATE workflows 
SET graph = REPLACE(
    graph, 
    '"provider_name": "<workflow_tool_id>"', 
    '"type": "workflow", "provider_name": "<workflow_tool_id>"'
)
WHERE graph LIKE '%<workflow_tool_id>%';
```

This must be done for every workflow-as-tool ID found in `tool_workflow_providers` and for every workflow version.

## Environment Details

- **OS:** Ubuntu 24.04
- **Docker Compose deployment**
- **Upgrade path:** 1.9.1 → 1.12.1
- **Plugin daemon:** running, healthy
- **Agent Strategy plugin:** langgenius/agent v0.0.31 (installed and working)
- **DB migrations:** all applied up to `788d3099ae3a` (head)
- **Affected components:** All Agent nodes using workflow-as-tools (FunctionCalling and ReAct strategies)

## Additional Context

- The issue affects **all** workflow-as-tools, not just specific ones (21 tools in our case)
- Regular marketplace plugins work correctly in Agent nodes
- The workflow-as-tools work correctly when used in **Tool nodes** (not Agent nodes)
- The `flask extract-plugins` / `install-plugins` / `migrate-data-for-plugin` migration commands do not handle workflow-as-tools in Agent node configurations
- Adding new workflow-as-tools to Agent nodes via the UI also does not save the `type` field, so the problem persists for new configurations as well

### LINKED ISSUE #32198: PluginNotFoundError: plugin not found
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.21.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have upgraded the service to 1.21.1, but I am still encountering the PluginNotFoundError: plugin not found issue. This tool is the one I published as a workflow. Has this issue been resolved for sure?

Image

### ✔️ Expected Behavior

do job

### ❌ Actual Behavior

Image

Image

### LINKED ISSUE #32204: Agent node drops type: mcp for MCP tools on save, causing PluginNotFoundError at runtime
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When adding or toggling MCP tools in an Agent node, the frontend does not persist the `type` field in the tool configuration. At runtime, `agent_node.py:262` reads `tool.get("type",
  ToolProviderType.BUILT_IN)`, which defaults to `builtin` when `type` is missing. This causes the runtime to call `get_builtin_provider` instead of `get_mcp_provider_controller`,
  resulting in `PluginNotFoundError: plugin not found`.

  The same MCP tool works correctly as a standalone Tool node in the same workflow.

  ## Steps to reproduce

  1. Create a workflow with an Agent node (FunctionCalling strategy)
  2. Add an MCP tool (e.g. `quick_search`) to the Agent's tool list
  3. Save and run the workflow
  4. Agent node fails with `PluginNotFoundError: plugin not found`

 
## Workaround

  Export the workflow DSL, manually add type: mcp to each MCP tool entry inside the Agent node's tools array, re-import. Any subsequent GUI edit to the Agent's tool list strips the type
  field again.

 ## Environment

  - Dify version: 1.12.1
  - Plugin Daemon: 0.5.3-local
  - Deployment: self-hosted Docker

### ✔️ Expected Behavior

 Agent node should persist `type: mcp` for MCP tools and resolve them via `get_mcp_provider_controller` at runtime.

### ❌ Actual Behavior

  `type` field is missing from the serialized tool config. Runtime defaults to `builtin`, calls `get_builtin_provider`, which fails with `PluginNotFoundError`.

  ## Root cause

  `api/core/workflow/nodes/agent/agent_node.py` line 262:

  ```python
  provider_type = ToolProviderType(tool.get("type", ToolProviderType.BUILT_IN))
```
 The frontend never writes type: mcp when serializing MCP tools in agent nodes.

### PR DESCRIPTION
**Pull request by fatelei**
> [!IMPORTANT]
>
> 1. Make sure you have read our [contribution guidelines](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md)
> 1. Ensure there is an associated issue and you have been assigned to it
> 1. Use the correct syntax to link this PR: `Fixes #<issue number>`.

## Summary

fix #32005
fix https://github.com/langgenius/dify/issues/32204
fix https://github.com/langgenius/dify/issues/32198
fix https://github.com/langgenius/dify/issues/32149

## Screenshots

| Before | After |
|--------|-------|
| ... | ... |

## Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `make lint` and `make type-check` (backend) and `cd web && npx lint-staged` (frontend) to appease the lint gods

### CODE REVIEW

**Review by zxhlyh — DISMISSED** [review]

File: web/app/components/workflow/block-selector/types.ts [hunk 1]
```diff
@@ -87,6 +87,7 @@ export type ToolValue = {
   enabled?: boolean
   extra?: { description?: string } & Record<string, unknown>
   credential_id?: string
+  type?: string
```
Comment (QuantumGhost) [inline web/app/components/workflow/block-selector/types.ts:90]: Maybe we should mark the `type` field as required?

Comment (fatelei) [reply web/app/components/workflow/block-selector/types.ts:90]: Written in the previous style

**Review by zxhlyh — APPROVED** [review]
