### PR TITLE
fix: fix cannot select stream-tool-call in agent modal

### LINKED ISSUE #16613: No module found in "" when i use agent node in chatflow
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Image

### ✔️ Expected Behavior

_No response_

### ❌ Actual Behavior

I added DeepSeek-R1 as system LLM，its working well when i use chatflow,agent,workflow and other apps except agent node in chatflow and workflow。
My agent strategy is dify agent strategy 0.0.9. I also tried other agent strategy in plugins marketplace and its not working either。

### LINKED ISSUE #17012: I could not select  my stream-tool-call in Agent plugin.
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

v1.1.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

install tools and then select in agent 

Image

Image

someone lose it

Image

### ✔️ Expected Behavior

I can get my stream-tool-call

### ❌ Actual Behavior

cannot find them.

### PR DESCRIPTION
**Pull request by LeeeeeeM**
# Summary

fix lost  tool-call enum: stream-tool-call, so we can select stream-tool-call in agent 

Close https://github.com/langgenius/dify/issues/16613
Fixes #17012

# Screenshots

| Before | After |
|--------|-------|
| image | image |

# Checklist
image
this backend enum for tool-call

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

File: web/app/components/header/account-setting/model-provider-page/declarations.ts [hunk 1]
```diff
@@ -55,6 +55,7 @@ export enum ModelFeatureEnum {
   toolCall = 'tool-call',
   multiToolCall = 'multi-tool-call',
   agentThought = 'agent-thought',
+  streamToolCall = 'stream-tool-call',
```
Comment (LeeeeeeM) [inline web/app/components/header/account-setting/model-provider-page/declarations.ts:58]: match backend enum

**Comment by LeeeeeeM** [comment]
@crazywoola  CC

**Review by crazywoola — APPROVED** [review]
