### PR TITLE
fix: ensure consistent DSL export behavior across UI entry

### LINKED ISSUE #24884: Export DSL not exporting current graph
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

Create a flow -> add nodes -> export the DSL soon after adding the latest node

### ✔️ Expected Behavior

Current draft should be saved, then export should be executed

### ❌ Actual Behavior

Export relies on latest auto-save version and the DSL may not be the same you were seeing in the draft editor

### PR DESCRIPTION
**Pull request by Kritoooo**
…points

> [!IMPORTANT]
>
> 1. Make sure you have read our [contribution guidelines](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md)
> 1. Ensure there is an associated issue and you have been assigned to it
> 1. Use the correct syntax to link this PR: `Fixes #<issue number>`.

## Summary

fix #24884 

The problem identified is that there are two different DSL export implementations with inconsistent behavior:

Right-click context menu export panel-contextmenu.tsx:114-117 - properly syncs workflow state before export
Top-left sidebar menu export app-info.tsx:135-152 - directly exports without syncing state

## Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

File: web/app/components/app-sidebar/app-info.tsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ import { NEED_REFRESH_APP_LIST_KEY } from '@/config'
 import { getRedirection } from '@/utils/app-redirection'
 import type { EnvironmentVariable } from '@/app/components/workflow/types'
 import { fetchWorkflowDraft } from '@/service/workflow'
+import { useNodesSyncDraft } from '@/app/components/workflow/hooks/use-nodes-sync-draft'
```
Comment (Kritoooo) [inline web/app/components/app-sidebar/app-info.tsx]: Due to context inconsistency, doSyncWorkflowDraft cannot function properly here; a better approach would be to prompt the user to save.

**Comment by Kritoooo** [comment]
image like this

**Review by crazywoola — APPROVED** [review]
