### PR TITLE
fix:#18447:When variables in the workflow are deleted or modified, it is impossible to visually identify subsequent node errors 

### LINKED ISSUE #18447: When variables in the workflow are deleted or modified, it is impossible to visually identify subsequent node errors
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.2.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

**The main issue is that it is complex to troubleshoot problems when there are a large number of nodes, and similar problems also exist in other types of nodes. The following is the simplest reproduction situation：**

**TakeKnowledge retrieval nodes as an example**：
1. Add a start variable, and the variable name is "start"
2. Add the Knowledge retrieval node and select the previously configured start variable "start" in the context configuration of the Knowledge retrieval node
3. Delete the connection between the LLM and the start node, and modify the "start" variable in the start variable
4. Connect the start node and the Knowledge retrieval node, add the end node, and click Publish
5. At this point, an error was found during operation, but there was no prompt in the page configuration

**Screenshot display**：

Image

Image

### ✔️ Expected Behavior

If an unobtainable variable is used in a node, the variable can be automatically deleted or prompted before publication；

### ❌ Actual Behavior

It wasn't deleted and there was no prompt. The problem to be investigated is complicated

### PR DESCRIPTION
**Pull request by tinet-dongfb**
Resolves #18447 

see [documentation](https://github.com/langgenius/dify/issues/18447) for more details.

# Screenshots

| Before | After |
|--------|-------|
| ...    | ...   |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]
LGTM

File: web/app/components/workflow/utils/workflow.ts [hunk 1]
```diff
@@ -327,3 +356,48 @@ export const getParallelInfo = (nodes: Node[], edges: Edge[], parentNodeId?: str
...
+export const getNotExistVariablesByArray = (array: string[][], varMap: Record<string, Var>) => {
+  if (!array.length)
+    return []
+  const var_warnings: string[] = []
+  array.forEach((item) => {
+    if (!item.length)
+      return
+    if (['sys'].includes(item[0]))
+      return
+    const var_warning = varMap[item.join('.')]
```
Comment (LeeeeeeM) [inline web/app/components/workflow/utils/workflow.ts:395]: item.join is undefined
