### PR TITLE
Fix/variable input validation issue

### LINKED ISSUE #23297: Node variable name input validation error
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Image

In the above scheenshot, when user purpose to input `result*`, the error will be triggered when typing `t`.

### ✔️ Expected Behavior

Validation should be triggered on blur or with debounced input checking.

### ❌ Actual Behavior

The validation is triggered on each keyboard input event.

### PR DESCRIPTION
**Pull request by MatriQ**
> [!IMPORTANT]
>
> 1. Make sure you have read our [contribution guidelines](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md)
> 2. Ensure there is an associated issue and you have been assigned to it
> 3. Use the correct syntax to link this PR: `Fixes #<issue number>`.

## Summary

Fix #23297

## Screenshots

https://github.com/user-attachments/assets/18fe6c6a-40a5-46f9-be04-a85fc3f7fdc8

## Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

File: web/app/components/base/toast/index.tsx [hunk 1]
```diff
@@ -29,6 +29,10 @@ type IToastContext = {
   close: () => void
 }
 
+export type ToastHandle = {
```
Comment (MatriQ) [inline web/app/components/base/toast/index.tsx:32]: Currently, the toast component can't not be proactively closed, the current fix is a temporiry solution. I plan to optimize it in the future.

File: web/app/components/base/toast/index.tsx [hunk 2]
```diff
@@ -46,7 +50,7 @@ const Toast = ({
 
   return <div className={classNames(
     className,
-    'fixed w-[360px] rounded-xl my-4 mx-8 flex-grow z-[9999] overflow-hidden',
+    'fixed z-[9999] mx-8 my-4 w-[360px] grow overflow-hidden rounded-xl',
```
Comment (MatriQ) [inline web/app/components/base/toast/index.tsx:53]: It just rearranges classes and replace `flex-grow` with `grow`

**Review by crazywoola — APPROVED** [review]
