### PR TITLE
feat: Move to node in workflow panel and fix help link hover style

### LINKED ISSUE #19997: Move the canvas to the center of the currently selected node
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

1. When I move the canvas to another position after opening the panel of a node, I need to quickly move the node back to the center of the canvas
2. When I move the canvas to another position by variable jumping, I need to quickly move the node back to the center of the canvas

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by wellCh4n**
# Summary

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

close #19997 

# Screenshots

| Before | After |
|--------|-------|
| x   | PixPin_2025-05-20_19-14-28   |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

File: web/app/components/workflow/nodes/_base/panel.tsx [hunk 1]
```diff
@@ -150,6 +151,7 @@ const BasePanel: FC<BasePanelProps> = ({
                   </Tooltip>
                 )
               }
+              <NodePosition nodeId={id}></NodePosition>
```
Comment (crazywoola) [inline web/app/components/workflow/nodes/_base/panel.tsx]: Suggestion:
Use data directly in `NodePosition `, so that you don't need to get the node by `const node = reactflow.getNode(nodeId)`

File: web/app/components/workflow/nodes/_base/components/node-position.tsx [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+  const position = node.position
+
+  return (
+    <TooltipPlus
+      popupContent={t('workflow.panel.moveToThisNode')}
+    >
+      <div
+        className='mr-1 flex h-6 w-6 cursor-pointer items-center justify-center  rounded-md hover:bg-state-base-hover'
+        onClick={() => {
+          setViewport({
```
Comment (crazywoola) [inline web/app/components/workflow/nodes/_base/components/node-position.tsx:40]: Please sync the draft after this operation `setViewport`.

Comment (wellCh4n) [reply web/app/components/workflow/nodes/_base/components/node-position.tsx:40]: I add `doSyncWorkflowDraft()` after setViewport.

**Review by crazywoola — APPROVED** [review]
