### PR TITLE
Fix vs code and using min version after bump @remixicon/react and @monaco-editor/loader

### LINKED ISSUE #27007: Bump @remixicon/react from 4.6.0 to 4.7.0 will break Code Block node
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Bump @monaco-editor/loader from 1.5.0 to 1.6.1 or @remixicon/react from 4.6.0 to 4.7.0
2. Open `Code block` and will found the code inside won't show and always display `Loading...`

### ✔️ Expected Behavior

Code block will display code

### ❌ Actual Behavior

Code block can not display code

### PR DESCRIPTION
**Pull request by Eric-Guo**
## Summary

Fixes #27007 by using min version of vs code

## Checklist

- [x] This change *not* requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added no test for the change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] No need to updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

@codex Kindly review this PR for the world peace!

### CODE REVIEW

File: web/public/vs/language/html/monaco.contribution.js [hunk 1]
```diff
@@ -0,0 +1 @@
...ines:!0,maxPreserveNewLines:void 0,indentHandlebars:!1,endWithNewline:!1,extraLiners:"head, body, /html",wrapAttributes:"auto"},suggest:{},data:{useDefaultDataProvider:!0}};function o(e){return{completionItems:!0,hovers:!0,documentSymbols:!0,links:!0,documentHighlights:!0,rename:!0,colors:!0,foldingRanges:!0,selectionRanges:!0,diagnostics:e===a,documentFormattingEdits:e===a,documentRangeFormattingEdits:e===a}}const a="html",m="handlebars",h="razor",g=r(a,s,o(a)),b=g.defaults,l=r(m,s,o(m)),L=l.defaults,d=r(h,s,o(h)),v=d.defaults;u.languages.html={htmlDefaults:b,razorDefaults:v,handlebarDefaults:L,htmlLanguageService:g,handlebarLanguageService:l,razorLanguageService:d,registerHTMLLanguageService:r};function S(){return new Promise((e,t)=>D(["../../htmlMode-DtjCNH-N"],e,t))}function r(e,t=s,c=o(e)){const i=new p(e,t,c);let f;const C=u.languages.onLanguage(e,async()=>{f=(await S()).setupMode(i)});return{defaults:i,dispose(){C.dispose(),f?.dispose(),f=void 0}}}n.handlebarDefaults=L,n.handlebarLanguageService=l,n.htmlDefaults=b,n.htmlLanguageService=g,n.razorDefaults=v,n.razorLanguageService=d,n.registerHTMLLanguageService=r,Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})}));
```
[the remark this answers is not in the document]
Comment (Eric-Guo) [reply web/public/vs/language/html/monaco.contribution.js:1]: `web/public/vs/htmlMode-DtjCNH-N.js` is existing if `web/public/vs/language/html/monaco.contribution.js` point via "../../htmlMode-DtjCNH-N"

**Comment by Eric-Guo** [comment]
@codex Kindly review this PR for the world peace!

File: web/public/vs/loader.js [hunk 2]
```diff
@@ -1,11 +1,1366 @@
-"use strict";/*!-----------------------------------------------------------
+'use strict';
+/*!-----------------------------------------------------------
  * Copyright (c) Microsoft Corporation. All rights reserved.
- * Version: 0.46.0(21007360cad28648bdf46282a2592cb47c3a7a6f)
+ * Version: 0.42.0-dev-20230906(e7d7a5b072e74702a912a4c855a3bda21a7757e7)
```
Comment (Eric-Guo) [inline web/public/vs/loader.js:4]: The whole vs folder is replaced by @codex with this version, I don't known why @codex choose this version, but seems we can avoid seeing min-maps/vs/loader.js.map missing in the Browser console.

File: web/eslint.config.mjs [hunk 3]
```diff
@@ -3,7 +3,6 @@ import {
   stylistic, typescript, unicorn,
 } from '@antfu/eslint-config'
 import globals from 'globals'
-import storybook from 'eslint-plugin-storybook'
```
Comment (Eric-Guo) [inline web/eslint.config.mjs:6]: Have to remove `eslint-plugin-storebook` to resolve `pnpm run lint` error:

> dify-web@1.9.1 lint /Users/guochunzhong/git/sso/dify/web
> eslint --cache --cache-location node_modules/.cache/eslint/.eslint-cache


Oops! Something went wrong! :(

ESLint: 9.37.0

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'eslint-plugin-storybook' imported from /Users/guochunzhong/git/sso/dify/web/eslint.config.mjs
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:266:9)
    at packageResolve (node:internal/modules/esm/resolve:767:81)
    at moduleResolve (node:internal/modules/esm/resolve:853:18)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:731:20)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:708:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:310:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:183:49)
 ELIFECYCLE  Command failed with exit code 2.


Which introduced at 403e2d58b96794727789609e41505c33374f9079, #13836

**Comment by Eric-Guo** [comment]
• Code Editor Failures After Dependency Bumps

  - Upgrading @monaco-editor/loader to 1.6.1 breaks code-editor/index.tsx because the loader now expects the AMD loader for Monaco 0.54.x. In 1.6.1 the success callback unwraps require(['vs/editor/editor.main'], fn) as ({ m }), whereas our local bundle in public/vs/ editor/editor.main.js is still Monaco 0.46.0 and returns the editor namespace directly. The callback therefore receives undefined, so handleEditorDidMount blows up as soon as it calls monaco.editor.setTheme(...).
    – Fix: refresh the shipped assets so the loader and static files are in lock-step. Download the 0.54.0 AMD build (npm pack monaco-
  editor@0.54.0) and replace public/vs/**, then keep loader.config({ paths: { vs: … } }) pointing at the new bundle. As a stop-gap you
  can wrap the mount handler with const resolved = monaco?.editor ? monaco : monaco?.m ?? window.monaco; before using it, but aligning the
  assets is the long-term answer.
    – Double-check any CDN/base-path overrides after the swap; the newer bundle ships hashed worker names, so you must copy the whole vs tree.
  - Jumping to @remixicon/react 4.7.0 introduces a different class of failure: the package still exports every icon from a single CJS/ESM entry point, but our next.config.js opts into experimental.optimizePackageImports for @remixicon/react. With 4.7.x Turbopack/Next rewrites
  import { RiCollapseDiagonalLine } into per-member imports that don’t actually exist, so the icon import resolves to undefined and React
  throws “Element type is invalid…” when ToggleExpandBtn renders—taking the editor chrome down with it.
    – Fix options: (1) drop @remixicon/react from the optimizePackageImports list (or guard it behind an environment check) so Next leaves the import alone; (2) if you need per-icon tree-shaking, swap to the generated local icons under app/components/base/icons and stop hitting the upstream package inside hot paths like the editor toolbar; or (3) pin @remixicon/react to 4.6.x until the upstream package exposes per-icon subpath exports.

  Next steps

  1. Replace public/vs with the 0.54.x distribution and re-run a smoke test on the workflow editor.
  2. Adjust next.config.js (or your icon usage) to keep the Remixicon optimizer from emitting missing subpaths, then run yarn dev to confirm
  the editor header renders without runtime errors.


› Do it for me.


• Updated the Monaco static bundle to the 0.54.0 AMD build so @monaco-editor/loader 1.6.1 can resolve the hashed module exports correctly, and tweaked the Next.js optimizer so Remixicon icons keep their CJS entry point.

  - public/vs: replaced the entire tree with the 0.54.0 contents (loader.js, editor/editor.main.js, hashed workers, nls files, etc.) that ship with the new loader, ensuring our local path ${basePath}/vs now exposes the modules the loader expects.
  - next.config.js:114-118 trims @remixicon/react from experimental.optimizePackageImports, preventing Next/Turbopack from rewriting icon imports into nonexistent per-icon files.

**Comment by Eric-Guo** [comment]
@codex Kindly review

File: web/public/vs/loader.js (hunk 2 above)
Comment (WTW0313) [reply web/public/vs/loader.js:4]: image

I have tried restoring this file, it seems no errors displayed in browser console.

Comment (WTW0313) [reply web/public/vs/loader.js:4]: Oh, I see. I manually copied vs folder in monaco-editor to `./public`, and in version 0.54.0, in loader.js the Version is set to `Version: 0.42.0-dev-20230906(e7d7a5b072e74702a912a4c855a3bda21a7757e7)`.

**Review by WTW0313 — APPROVED** [review]
LGTM

**Review by crazywoola — APPROVED** [review]
