### PR TITLE
fix(web): fix document detail page status inconsistency with list page

### LINKED ISSUE #33759: document detail page status inconsistency with list page
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.32

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Upload multiple documents. The document parsing status changes to Available, but when you click into it, it still shows Parsing.
After entering the document and finishing parsing, the document list remains in Indexing status.
At **17s** in the video, **page_45.pdf** shows as **Available**, but at **26s** when clicked into, it is **still Indexing**.
The same issue occurs with **page_44.pdf** at **44s** in the video.

https://github.com/user-attachments/assets/b034de72-a7a4-496d-9951-5dc040eae147

### ✔️ Expected Behavior

The two states remain consistent.

### ❌ Actual Behavior

The document statuses in the two places are inconsistent.

### PR DESCRIPTION
**Pull request by fisherOne1**
Fix: https://github.com/langgenius/dify/issues/33759
## Summary
- The document detail page (`datasets/{id}/documents/{docId}`) incorrectly showed "available" status while the document list page (`datasets/{id}/documents`) correctly showed "indexing", caused by a `|| 'available'` fallback rendering before data loaded.
- Guard `StatusItem` behind a `documentDetail` loaded check to prevent the false default.
- Add `refetchInterval` to `useDocumentDetail` for non-terminal statuses (queuing/indexing/paused) so the detail page polls every 2.5s, consistent with the list page.
- Memoize inline object props and wrap callbacks with `useCallback` to prevent unnecessary re-renders.

### CODE REVIEW

**Comment by WTW0313** [comment]
Hello, @fisherOne1 . Could you please create a new issue to document this problem in detail? If no related issues currently exist, kindly ensure the issue is created and then link it to this pull request.

**Comment by fisherOne1** [comment]
@WTW0313 i have create a issue at https://github.com/langgenius/dify/issues/33759 and upload a video to show.

**Review by themavik — COMMENTED** [review]
nice, the refetchInterval while status is non-terminal plus the documentDetail guard should fix the status inconsistency

File: web/app/components/datasets/documents/detail/index.tsx [hunk 1]
```diff
@@ -32,6 +32,12 @@ type DocumentDetailProps = {
   documentId: string
 }
 
+const NON_TERMINAL_DISPLAY_STATUSES = new Set(['queuing', 'indexing', 'paused'])
```
Comment (crazywoola) [inline web/app/components/datasets/documents/detail/index.tsx]: You can use this instead

https://github.com/langgenius/dify/blob/6fff46bc29891cd9a26a65391076c97554fab2c6/web/models/datasets.ts#L311-L320

**Review by crazywoola — COMMENTED** [review]
See comments

**Review by WTW0313 — APPROVED** [review]

**Review by crazywoola — APPROVED** [review]
