### PR TITLE
fix: Add vertical scrolling support for floating elements.

### LINKED ISSUE #30882: No scrollbar appearing, preventing the selection of the overflowed properties below.
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.11.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Image

### ✔️ Expected Behavior

The content in the variable selection box on the left is extensive, so scroll bars are expected to appear vertically.

### ❌ Actual Behavior

There is no scrollbar appearing, preventing the selection of the overflowed properties below.

### PR DESCRIPTION
**Pull request by coopercoder**
## Summary

fixes #30882
close #30909

fix
The content in the variable selection box on the left is extensive, so scroll bars are expected to appear vertically.
but there is no scrollbar appearing, preventing the selection of the overflowed properties below.
this fix resolve this problem

## Screenshots

| Before | After |
|--------|-------|
| 
534891446-900d1793-3765-4b7e-86ab-62bfb6e8eba9
 | 
image
 |

## Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `make lint` and `make type-check` (backend) and `cd web && npx lint-staged` (frontend) to appease the lint gods

### CODE REVIEW

File: web/app/components/base/portal-to-follow-elem/index.tsx [hunk 1]
```diff
@@ -61,9 +61,12 @@ export function usePortalToFollowElem({
       }),
       shift({ padding: 5 }),
       size({
-        apply({ rects, elements }) {
-          if (triggerPopupSameWidth)
-            elements.floating.style.width = `${rects.reference.width}px`
+        apply({ rects, elements, availableHeight }) {
+          Object.assign(elements.floating.style, {
+            maxHeight: `${availableHeight}px`,
```
Comment (hyoban) [inline web/app/components/base/portal-to-follow-elem/index.tsx]:
```suggestion
            maxHeight: `${Math.max(0, availableHeight)}px`,
```

**Review by hyoban — DISMISSED** [review]

**Comment by hyoban** [comment]
Actually, I can not reproduce your issue. What browser are you using? Or what step am I missing?

CleanShot 2026-01-22 at 17 50 06@2x

**Comment by coopercoder** [comment]
> Actually, I can not reproduce your issue. What browser are you using? Or what step am I missing?
> 
> CleanShot 2026-01-22 at 17 50 06@2x


@hyoban  you can try this by import this dsl 
[test.yml](https://github.com/user-attachments/files/24854556/test.yml)

image

**Review by hyoban — APPROVED** [review]
