### PR TITLE
Bugfix: Windows compatibility issue with 'cp' command not found when running pnpm start. (#25670)

### LINKED ISSUE #25670: Windows Compatibility Issue: 'cp' command not found when running pnpm start
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

> dify-web@1.8.1 start .\dify\web > cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && cross-env PORT=$npm_config_port HOSTNAME=$npm_config_host node .next/standalone/server.js  'cp' is not recognized as an internal or external command, operable program or batch file.  ELIFECYCLE  Command failed with exit code 1.

### Cloud or Self Hosted

Self Hosted (Source)

## Bug Description
When attempting to start the Dify web application on Windows using `pnpm start`, the command fails with the error "'cp' is not recognized as an internal or external command, operable program or batch file." This is because the `cp` command used in the start script is a Unix/Linux command that doesn't exist natively on Windows.

## Steps to Reproduce
1. Clone the Dify repository on a Windows machine
2. Navigate to the `web` directory
3. Run `pnpm install` to install dependencies
4. Run `pnpm build` to build the application
5. Run `pnpm start` to start the application
6. Observe the error

### ✔️ Expected Behavior

The application should start successfully on Windows, just like it does on Unix-like systems.

### ❌ Actual Behavior

The command fails with the error:
```
'cp' is not recognized as an internal or external command, operable program or batch file.
```

### PR DESCRIPTION
**Pull request by gin-melodic**
…ing pnpm start. (#25670)

- Replace the existing start script in package.json with a reference to a new copy-and-start.mjs file
- Add new copy-and-start.mjs script to handle copying static files and starting the server
- Improve error handling and logging for the start process
- Make the script more configurable with environment variables

> [!IMPORTANT]
>
> 1. Make sure you have read our [contribution guidelines](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md)
> 1. Ensure there is an associated issue and you have been assigned to it
> 1. Use the correct syntax to link this PR: `Fixes #<issue number>`.

## Summary

This PR addresses issue #25670 which fixes a Windows compatibility problem where the 'cp' command was not found when running `pnpm start`. The issue occurred because the original start script in package.json used Unix-specific `cp` commands that are not available on Windows systems.

To resolve this cross-platform compatibility issue, I've replaced the simple shell commands with a Node.js script (`copy-and-start.mjs`) that performs the same file copying operations using Node's built-in `fs` module, which works consistently across all platforms.

The new script:
1. Copies static files from `.next/static` to `.next/standalone/.next/static`
2. Copies public resources from `public` to `.next/standalone/public`
3. Starts the server with configurable host and port via environment variables
4. Includes proper error handling and logging

This change ensures that Dify web application can be built and started successfully on both Unix-like systems and Windows systems without requiring additional tools or shell compatibility layers.

Fixes #25670

## Screenshots

| Before | After |
|--------|-------|
| image |  image  |

(Note: These are representative images showing the error that was occurring and the successful result after the fix)

## Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

File: web/scripts/copy-and-start.mjs [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+// Ensure target directories exist
+ensureDir(staticDestDir)
+ensureDir(publicDestDir)
+
+// Copy static files
+if (existsSync('.next/static'))
+  copyDir('.next/static', staticDestDir)
+else
+  console.log('Warning: .next/static directory does not exist')
```
Comment (asukaminato0721) [inline web/scripts/copy-and-start.mjs]:
```suggestion
  console.warn('Warning: .next/static directory does not exist')
```

File: web/scripts/copy-and-start.mjs [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+
+// Copy public resources
+if (existsSync('public'))
+  copyDir('public', publicDestDir)
+else
+  console.log('Warning: public directory does not exist')
```
Comment (asukaminato0721) [inline web/scripts/copy-and-start.mjs]:
```suggestion
  console.warn('Warning: public directory does not exist')
```

[the remark this answers is not in the document]
Comment (gin-melodic) [reply web/scripts/copy-and-start.mjs]: Use path.join: Constructing paths with path.join ensures cross-platform compatibility. 
Good suggestions, I have updated the code accordingly.

Centralize path definitions: Grouping all path-related constants at the top makes the script easier to read and modify.
Good suggestions, I have updated the code accordingly.

Don't Repeat Yourself (DRY): The logic for copying directories is repeated. This can be refactored into a loop over a configuration array, which makes the code cleaner and easier to extend.
Good suggestions, I have updated the code accordingly.

Use braces for control flow: Adding curly braces to if/else statements is a good practice to improve readability and prevent potential bugs.
Because of the `'curly': ['error', 'multi-or-nest', 'consistent'],` rule in `eslint.config.mjs`, I could not add curly braces to the if/else statements.

File: web/scripts/copy-and-start.mjs [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+// Start server
+const port = process.env.npm_config_port || process.env.PORT || '3000'
+const host = process.env.npm_config_host || process.env.HOSTNAME || 'localhost'
+
+console.log(`Starting server on ${host}:${port}`)
+
+const server = spawn(
+  process.execPath,
+  ['.next/standalone/server.js'],
```
[the remark this answers is not in the document]
Comment (gin-melodic) [reply web/scripts/copy-and-start.mjs]: Good suggestions, I have updated the code accordingly.

File: web/scripts/copy-and-start.mjs (hunk 2 above)
Comment (gin-melodic) [reply web/scripts/copy-and-start.mjs]: Good suggestions, I have updated the code accordingly.

File: web/scripts/copy-and-start.mjs (hunk 1 above)
Comment (gin-melodic) [reply web/scripts/copy-and-start.mjs]: Good suggestions, I have updated the code accordingly.

File: web/scripts/copy-and-start.mjs [hunk 4]
```diff
@@ -0,0 +1,79 @@
+#!/usr/bin/env node
+/**
+ * This script copies static files to the target directory and starts the server.
+ * It is intended to be used as a replacement for `next start`.
+ */
+
+import { cpSync, existsSync, mkdirSync } from 'node:fs'
```
Comment (asukaminato0721) [inline web/scripts/copy-and-start.mjs]: How about fs/promises api ?

Comment (gin-melodic) [reply web/scripts/copy-and-start.mjs]: The file operations in the code have been replaced with the `fs/promises api` version

File: web/scripts/copy-and-start.mjs [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+}
+
+// Run copy operations and start server
+const main = async () => {
+  console.debug('Starting copy-and-start script')
+  await copyAllDirs()
+
+  // Start server
+  const port = process.env.npm_config_port || process.env.PORT || '3000'
+  const host = process.env.npm_config_host || process.env.HOSTNAME || 'localhost'
```
Comment (lyzno1) [inline web/scripts/copy-and-start.mjs]: Keep default hostname as 0.0.0.0
The new script hard-codes const host = ... || 'localhost', which means we now always pass HOSTNAME=localhost into the standalone server. Previously npm start only set
Please drop the 'localhost' default so we preserve the old behavior.

File: web/scripts/copy-and-start.mjs [hunk 6]
```diff
@@ -0,0 +1,113 @@
...
+
+// Process each directory copy operation
+const copyAllDirs = async () => {
+  console.debug('Starting directory copy operations')
+  for (const { src, dest } of DIRS_TO_COPY) {
+    try {
+      console.debug(`Ensuring destination directory exists: ${dest}`)
+      await mkdir(dest, { recursive: true })
+      if (await pathExists(src))
+        await copyDir(src, dest)
```
Comment (lyzno1) [inline web/scripts/copy-and-start.mjs]: Avoid double-nesting copied assets
    Because we call mkdir(dest, { recursive: true }) before cp(src, dest, { recursive: true }), the destination directories already exist when cp runs. In Node’s
  fs.promises.cp, when the destination path exists and is a directory, the source directory is copied inside it (i.e. .next/standalone/.next/static/static). The Next
  standalone server expects assets directly under .next/standalone/.next/static, so with this change every static asset 404s and the app fails to load. Please drop the pre-
  creation of the destination (or copy into its parent) so the copied directories land at the correct paths.

File: web/scripts/copy-and-start.mjs (hunk 5 above)
Comment (gin-melodic) [reply web/scripts/copy-and-start.mjs]: Thanks for the feedback. I'll get this fixed and push the update shortly.

File: web/package.json [hunk 7]
```diff
@@ -22,7 +22,7 @@
     "dev": "cross-env NODE_OPTIONS='--inspect' next dev --turbopack",
     "build": "next build",
     "build:docker": "next build && node scripts/optimize-standalone.js",
-    "start": "cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && cross-env PORT=$npm_config_port HOSTNAME=$npm_config_host node .next/standalone/server.js",
+    "start": "node scripts/copy-and-start.mjs",
```
Comment (lyzno1) [inline web/package.json]:
```suggestion
    "start": "node ./scripts/copy-and-start.mjs",
```

File: web/scripts/copy-and-start.mjs [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+    try {
+      // Instead of pre-creating destination directory, we ensure parent directory exists
+      const destParent = path.dirname(dest)
+      console.debug(`Ensuring destination parent directory exists: ${destParent}`)
+      await mkdir(destParent, { recursive: true })
+      if (await pathExists(src))
+        await copyDir(src, dest)
+      else
+        console.warn(`Warning: ${src} directory does not exist`)
+    }
```
Comment (lyzno1) [inline web/scripts/copy-and-start.mjs]: [P1] Fail fast when build artifacts missing
    In the previous start script the cp -r .next/static … command aborted the process whenever the build artifacts were missing. In the new script we only log a warning when pathExists(src) is false and
  proceed to start the server anyway. If .next/static (or even public) is absent—e.g. when someone forgets to run pnpm build, or the build step fails—the server now boots successfully but serves none of
  the static assets, resulting in a blank/broken UI instead of a hard failure. Could we keep the old fail-fast behavior by exiting with a non-zero status when these directories are missing?

**Review by lyzno1 — APPROVED** [review]
