### PR TITLE
fix: tools edit modal schema edit issue

### LINKED ISSUE #6395: tools edit modal => editing schema cause cursor goto end
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

check this video please.

https://github.com/user-attachments/assets/0febad04-d0aa-4eec-801a-68960d323697

### ✔️ Expected Behavior

Editing schema changes the current form context without moving my cursor to the end.

BTW, i fixed it in my localhost. please check my PR.

https://github.com/user-attachments/assets/10c1c9e8-e245-4d68-9619-505fd27cb933

### ❌ Actual Behavior

Editing causes my cursor to move to the end. very bad experience

### PR DESCRIPTION
**Pull request by qweasdzxcpkh**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] create api tools & save
- [x] edit api tools & save

fixed #6395

### CODE REVIEW

File: web/app/components/tools/edit-custom-collection-modal/index.tsx [hunk 1]
```diff
@@ -87,16 +87,17 @@ const EditCustomCollectionModal: FC<Props> = ({
       return
     }
     (async () => {
-      const customCollection = getCustomCollection()
       try {
         const { parameters_schema, schema_type } = await parseParamsSchema(debouncedSchema)
+        const customCollection = getCustomCollection()
```
Comment (crazywoola) [inline web/app/components/tools/edit-custom-collection-modal/index.tsx:92]: I don't think it should be changed like this, and the code before the try catch should have the same effect as the current code. Maybe you should update the deps instead.

```
React Hook useEffect has missing dependencies: 'editFirst', 'getCustomCollection', 'isEdit', and 'setCustomCollection'. Either include them or remove the dependency array.
```


```
  useEffect(() => {
    if (!debouncedSchema)
      return
    if (isEdit && editFirst) {
      setEditFirst(false)
      return
    }
    (async () => {
      const customCollection = getCustomCollection()
      try {
        const { parameters_schema, schema_type } = await parseParamsSchema(debouncedSchema)
        const newCollection = produce(customCollection, (draft) => {
          draft.schema_type = schema_type
        })
        setCustomCollection(newCollection)
        setParamsSchemas(parameters_schema)
      }
      catch (e) {
        const newCollection = produce(customCollection, (draft) => {
          draft.schema_type = ''
        })
        setCustomCollection(newCollection)
        setParamsSchemas([])
      }
    })()
  }, [debouncedSchema, editFirst, getCustomCollection, isEdit, setCustomCollection])
```

**Review by crazywoola — CHANGES_REQUESTED** [review]

File: web/app/components/tools/edit-custom-collection-modal/index.tsx (hunk 1 above)
Comment (qweasdzxcpkh) [reply web/app/components/tools/edit-custom-collection-modal/index.tsx:92]: > the code before the try catch should have the same effect as the current code.

no, issue accur because `getCustomCollection` was called before await. assume this behavior in browser:
1. old = getCustomCollection() // {schema: "abc"}
2. user input change the value state // value is {schema: "abcd"} whatever
3. setCustomCollection(old) // value is old, user input change will be lost
4. Because the code set the old value to `schema`, in the meantime when I enter input, just cause the problem with #6395.

> Maybe you should update the deps instead.

This useEffect seems that logic is watching the `debouncedSchema`, if it changes, call api and parse params schema, it is totally a side effect, I think it is not a good idea to set other deps to trigger api call, i think the logic is clear?

Comment (crazywoola) [reply web/app/components/tools/edit-custom-collection-modal/index.tsx:92]: 👍

**Review by crazywoola — APPROVED** [review]
