### PR TITLE
Fix issues related to search apps, notification duration, and loading icon on the explore page

### LINKED ISSUE #4936: Notification position and duration
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes. On a large screen, the notification alert is hard to see - the alert duration is sometimes too short to be noticed.

Screenshot 2024-06-04 at 1 44 14 PM

### 2. Describe the feature you'd like to see

maybe center the alert window and make the duration longer (especially for error msg)

For example, the uploaded file size limit is 15m, when I uploaded a 40m file, I did not notice the error alert and was wondering what happened. notice

### 3. How will this feature improve your workflow or experience?

better notified.

### 4. Additional context or comments

_No response_

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### LINKED ISSUE #6263: Search Apps by Dify
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

It's hard to browse all the apps by Dify. 
Screenshot 2024-07-14 at 7 12 07 AM

It would be great if there is a simple search box like the GPT store:

Screenshot 2024-07-14 at 7 12 34 AM

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### LINKED ISSUE #6373: explore page not have loading icon
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Cloud

### Steps to reproduce

image

### ✔️ Expected Behavior

explore page need have loading icon

### ❌ Actual Behavior

The loading icon does not appear on the explore page when a request is made

### PR DESCRIPTION
**Pull request by faye1225**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Fixes #6263 ; About add search apps in explore
Fixes #4936 ; About notification duration too short
Fixes #6373 ; About explore page not have loading icon

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

File: web/app/components/app/configuration/debug/index.tsx [hunk 1]
```diff
@@ -136,19 +136,19 @@ const Debug: FC<IDebug> = ({
 
   const { notify } = useContext(ToastContext)
   const logError = useCallback((message: string) => {
-    notify({ type: 'error', message, duration: 3000 })
+    notify({ type: 'error', message, duration: 6000 })
```
Comment (crazywoola) [inline web/app/components/app/configuration/debug/index.tsx]: I suggest we could add a default value here, and remove all those pre-defined numbers, so that we do not need to edit those files later, since they are the same.
https://github.com/langgenius/dify/blob/eff280f3e79cf1f75d3b11338def71832905a8aa/web/app/components/base/toast/index.tsx#L120

**Review by crazywoola — CHANGES_REQUESTED** [review]
The rest LGTM, If you have further questions, please DM me on wechat: crazyphage.

**Comment by crazywoola** [comment]
image

File: web/app/components/app/configuration/debug/index.tsx (hunk 1 above)
Comment (faye1225) [reply web/app/components/app/configuration/debug/index.tsx]: Actually, the notify component already has a default value, with the duration set to 3000 by default. 
https://github.com/langgenius/dify/blob/eff280f3e79cf1f75d3b11338def71832905a8aa/web/app/components/base/toast/index.tsx#L92
However, I am not sure why most of the error messages specifically set it to 3000. On the 'Password Reset' page, the duration of notify is set to 5000.
https://github.com/langgenius/dify/blob/eff280f3e79cf1f75d3b11338def71832905a8aa/web/app/init/InitPasswordPopup.tsx#L35

**Comment by faye1225** [comment]
> image

done

File: web/app/components/app/configuration/debug/index.tsx (hunk 1 above)
Comment (crazywoola) [reply web/app/components/app/configuration/debug/index.tsx]: I guess it's because someone reported it before and only make that notification longer.

Comment (faye1225) [reply web/app/components/app/configuration/debug/index.tsx]: Perhaps we could consider changing the default value to 6000 and removing all the predefined numbers.

**Review by crazywoola — DISMISSED** [review]

**Review by crazywoola — APPROVED** [review]
