### PR TITLE
fix: delete app and setting modal is not wokring in firefox

### LINKED ISSUE #1270: 删除应用无反应
### Dify version

0.3.24

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

我是管理员，“构建应用”里试图删除某个应用无反应，无论是自己部署的，还是公有云版https://cloud.dify.ai/apps里都是如此。

### ✔️ Expected Behavior

可以删除应用

### ❌ Actual Behavior

_No response_

### PR DESCRIPTION
**Pull request by crazywoola**
Close #1270 @leslie2046

### CODE REVIEW

File: web/app/(commonLayout)/apps/AppCard.tsx [hunk 1]
```diff
@@ -133,8 +136,12 @@ const AppCard = ({ app, onRefresh }: AppCardProps) => {
 
   return (
     <>
-      <Link
-        href={`/app/${app.id}/overview`}
+      <div
+        // href={`/app/${app.id}/overview`}
```
Comment (crazywoola) [inline web/app/(commonLayout)/apps/AppCard.tsx]:
```suggestion
```

**Review by iamjoel — APPROVED** [review]
