### PR TITLE
fix(workflow/if-else): keep conditions in sync on variable rename 

### LINKED ISSUE #23460: IF/ELSE Node does not track variable rename
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create a workflow with an input parameter
Add an IF/ELSE Node that references that parameter
Rename the parameter

### ✔️ Expected Behavior

the rename should be reflected in the IF/ELSE Node

### ❌ Actual Behavior

Unlike other nodes, the rename is not tracked and the workflow will break

### PR DESCRIPTION
**Pull request by iamrajhans**
> [!IMPORTANT]
>
> 1. Make sure you have read our [contribution guidelines](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md)
> 2. Ensure there is an associated issue and you have been assigned to it
> 3. Use the correct syntax to link this PR: `Fixes #<issue number>`.

## Summary

fix #23460 

## Screenshots

| Before | After |
|--------|-------|
| ...    | ...   |

## Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Review by crazywoola — CHANGES_REQUESTED** [review]
It seems only sync the next/specific nodes instead of syncing all the occurrences across the workflow.

**Comment by iamrajhans** [comment]
@crazywoola could you please review once

File: web/app/components/workflow/hooks/use-workflow.ts [hunk 1]
```diff
@@ -259,10 +259,10 @@ export const useWorkflow = () => {
 
   const handleOutVarRenameChange = useCallback((nodeId: string, oldValeSelector: ValueSelector, newVarSelector: ValueSelector) => {
     const { getNodes, setNodes } = store.getState()
-    const afterNodes = getAfterNodesInSameBranch(nodeId)
-    const effectNodes = findUsedVarNodes(oldValeSelector, afterNodes)
+    const allNodes = getNodes()
+    const effectNodes = findUsedVarNodes(oldValeSelector, allNodes)
```
Comment (crazywoola) [inline web/app/components/workflow/hooks/use-workflow.ts]:
```suggestion
    const effectNodes = findUsedVarNodes(oldValeSelector, allNodes)
```

I think we should rename it to `affectedNodes`

**Review by crazywoola — APPROVED** [review]
